name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

# 📍 깃허브 페이지스 배포를 위해 필요한 보안 권한을 허용하는 핵심 설정!
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4